{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  type: {{ if $svc.nodePort }}NodePort{{ else }}ClusterIP{{ end }}
  selector:
    app: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      {{- if $svc.nodePort }}
      nodePort: {{ $svc.nodePort }}
      {{- end }}
{{- end }}
